---
title: "anova TEST"
output: html_document
date: "2023-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Add T10, T13, T15, T18 data frames
# Provide the file path
file_path1 <- "C:\\Users\\FHL Guest\\Documents\\GitHub\\nereosisters\\summed data\\T10 Data.csv"

# Read the CSV file
T10Data <- read.csv(file_path1)

file_path2 <- "C:\\Users\\FHL Guest\\Documents\\GitHub\\nereosisters\\summed data\\T13 Data.csv"

# Read the CSV file
T13Data <- read.csv(file_path2)

file_path3 <- "C:\\Users\\FHL Guest\\Documents\\GitHub\\nereosisters\\summed data\\T15 Data.csv"

# Read the CSV file
T15Data <- read.csv(file_path3)

file_path4 <- "C:\\Users\\FHL Guest\\Documents\\GitHub\\nereosisters\\summed data\\T18 Data.csv"

# Read the CSV file
T18Data <- read.csv(file_path4)
```



```{r}
# Sample data for four treatment groups
Sratio10 <- T10Data$female / T10Data$male
print(Sratio10)
Sratio13 <- T13Data$female / T13Data$male
print(Sratio13)
Sratio15 <- T15Data$female / T15Data$male
print(Sratio15)
Sratio18 <- T18Data$female / T18Data$male
print(Sratio18)
```



```{r}
meanSratio10 <- mean(Sratio10)
meanSratio13 <- mean(Sratio13, na.rm = TRUE)
meanSratio15 <- mean(Sratio15)
meanSratio18 <- mean(Sratio18, na.rm = TRUE)
print(meanSratio10)
print(meanSratio13)

print(meanSratio15)
print(meanSratio18)
```
```{r}


```

